In [39]:
%load_ext autoreload
%autoreload 2
import edhec_risk_kit as erk

rets = erk.get_hfi_returns()["2000":]
rets

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
2000-01                 0.0227      0.0128                 0.0088   
2000-02                 0.0267     -0.0022                 0.0421   
2000-03                 0.0243     -0.0138                 0.0103   
2000-04                 0.0223     -0.0241                -0.0101   
2000-05                 0.0149      0.0114                -0.0132   
...                        ...         ...                    ...   
2018-07                 0.0021     -0.0058                 0.0093   
2018-08                 0.0024      0.0166                 0.0002   
2018-09                 0.0034     -0.0054                 0.0050   
2018-10                -0.0073     -0.0314                -0.0158   
2018-11                -0.0068     -0.0053                -0.0193   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
2000-01            0.0077                 0.0075        0.0088   
2000-02            0.0528                 0.0253        0.0346   
2000-03            0.0318                 0.0134        0.0069   
2000-04           -0.0541                 0.0168       -0.0059   
2000-05           -0.0433                 0.0062       -0.0034   
...                   ...                    ...           ...   
2018-07            0.0040                -0.0010        0.0055   
2018-08           -0.0277                 0.0004        0.0011   
2018-09           -0.0110                -0.0016        0.0032   
2018-10           -0.0315                -0.0129       -0.0257   
2018-11            0.0120                -0.0211       -0.0034   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
2000-01                  0.0041        0.0021             0.0075   
2000-02                  0.0097        0.0408             0.0699   
2000-03                 -0.0061       -0.0104             0.0006   
2000-04                 -0.0006       -0.0304            -0.0201   
2000-05                  0.0107       -0.0070            -0.0097   
...                         ...           ...                ...   
2018-07                  0.0022       -0.0014             0.0067   
2018-08                  0.0017       -0.0007             0.0035   
2018-09                  0.0036        0.0006            -0.0023   
2018-10                 -0.0023       -0.0096            -0.0402   
2018-11                 -0.0067       -0.0087            -0.0044   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
2000-01            0.0143          0.0173         0.0427          0.0169  
2000-02            0.0239          0.0185        -0.1340          0.0666  
2000-03            0.0131          0.0163        -0.0230          0.0039  
2000-04            0.0188          0.0092         0.1028         -0.0269  
2000-05            0.0146          0.0080         0.0704         -0.0122  
...                   ...             ...            ...             ...  
2018-07           -0.0021          0.0045        -0.0052          0.0018  
2018-08            0.0050         -0.0002        -0.0214          0.0015  
2018-09            0.0028          0.0018         0.0036         -0.0022  
2018-10           -0.0080         -0.0109         0.0237         -0.0269  
2018-11            0.0119         -0.0063        -0.0021         -0.0071  

[227 rows x 13 columns]

Monthly Parametric VaR

In [6]:
erk.var_gaussian(rets["Distressed Securities"], level = 1)

0.03143017693928047

In [7]:
erk.var_gaussian(rets["Distressed Securities"], level = 1, modified =True)

0.04966909110627918

Historical VaR

In [8]:
erk.var_historic(rets["Distressed Securities"], level = 1)

0.042642

Loading Industry Returns

In [49]:
import numpy as np
l = ["Books", "Steel", "Oil", "Mines"]
ind = erk.get_ind_returns()["2013":"2017"][l]
er = erk.annualize_rets(ind, 12)
cov = ind.cov()
print(er)
cov

Books    0.095312
Steel    0.100716
Oil      0.025275
Mines    0.005136
dtype: float64


Books     Steel       Oil     Mines
Books  0.002720  0.001940  0.001637  0.001539
Steel  0.001940  0.004391  0.002122  0.003391
Oil    0.001637  0.002122  0.002697  0.002179
Mines  0.001539  0.003391  0.002179  0.005232

In [50]:
ew_w = np.repeat(1/er.shape[0], er.shape[0])
ew_w

array([0.25, 0.25, 0.25, 0.25])

In [51]:
msr_w = erk.msr(.1, er, cov)
msr_w

array([0.00000000e+00, 1.00000000e+00, 1.12757026e-17, 1.04950770e-16])

In [52]:
gmv = erk.gmv(cov)
gmv

array([0.47702486, 0.        , 0.43411204, 0.0888631 ])

In [54]:
ind_2018 = erk.get_ind_returns()["2018"][l]
cov_2018 = ind_2018.cov()
sigma_msr = erk.portfolio_vol(msr_w, cov_2018)
annualized_sigma_msr = sigma_msr*np.sqrt(12)
annualized_sigma_msr

0.21983988181484185

In [55]:
sigma_gmv= erk.portfolio_vol(gmv, cov_2018)
annualized_sigma_gmv=sigma_gmv*np.sqrt(12)
annualized_sigma_gmv

0.1897373462843658

In [56]:
ind_2018.cov()

Books     Steel       Oil     Mines
Books  0.002799  0.002098  0.002558  0.001629
Steel  0.002098  0.004027  0.003473  0.001843
Oil    0.002558  0.003473  0.005296  0.001961
Mines  0.001629  0.001843  0.001961  0.002059